module.exports = {
  apps: [
    {
      name: 'backend',
      script: 'npx',
      args: 'tsx server/index.ts',
      watch: false,
      autorestart: true,
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      min_uptime: '5s',
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        NODE_OPTIONS: '--max-old-space-size=1024 --unhandled-rejections=warn',
      },
      error_file: './logs/error.log',
      out_file: './logs/out.log',
      merge_logs: true,
      time: true,
      listen_timeout: 5000,
      kill_timeout: 5000,
      wait_ready: true,
    },
    {
      name: 'worker',
      script: 'npx',
      args: 'tsx server/worker.ts',
      watch: false,
      autorestart: true,
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1G',
      min_uptime: '5s',
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        NODE_OPTIONS: '--max-old-space-size=1024 --unhandled-rejections=warn',
      },
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};